services:
  - type: web
    name: login # Or keep your Render service name
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt" # <-- Uncommented
    gunicorn day_80_request.app:app
